# Generated by Django 5.2.4 on 2025-07-12 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menuitem',
            options={'ordering': ['nama'], 'verbose_name': 'Menu', 'verbose_name_plural': 'Daftar Menu'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-tanggal_pesan']},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'Item Pesanan', 'verbose_name_plural': 'Daftar Item Pesanan'},
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='deskripsi',
            field=models.TextField(blank=True, null=True, verbose_name='Deskripsi'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='gambar',
            field=models.ImageField(blank=True, null=True, upload_to='menu/', verbose_name='Gambar Menu'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='harga',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Harga'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='nama',
            field=models.CharField(max_length=100, verbose_name='Nama Menu'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('menunggu', 'Menunggu Pembayaran'), ('diproses', 'Diproses'), ('dikirim', 'Dikirim'), ('selesai', 'Selesai')], default='menunggu', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='order',
            name='tanggal_pesan',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Tanggal Pesan'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='Jumlah'),
        ),
    ]
